DetailedErrors: true
Logging: 
  LogLevel: 
    Default: Information
    Microsoft.AspNetCore: Information
MongoDB: 
  # ConnectionURI: mongodb://admin:admin@localhost:27017/audit_trail?authSource=admin
  ConnectionURI: mongodb://admin:admin@localhost:27017
  DatabaseName: audit_trail
  CollectionName: logs
